nodeLinker: node-modules
compressionLevel: mixed
enableGlobalCache: false
enableInlineHunks: true
enableColors: true

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - current
    - x64
    - ia32
    - arm64
  libc:
    - current
    - glibc
    - musl

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

yarnPath: .yarn/releases/yarn-4.4.1.cjs
