packages:
  - "sites/twin.run"
  - "packages/*"
  - "packages/dev-tools/webui"
  - "apps/*"

catalog:
  expo: ~51.0.39
  react: ~18.2.0
  react-dom: ~18.2.0
  react-native: 0.74.5
  react-native-web: ~0.19.10
  next: ^14.2.3
  "@types/react": ~18.2.79
  "@types/react-dom": ~18.2.25
  
catalogs:
  effect:
    effect: ^3.10.0
    "@effect/platform": ^0.69.3
    "@effect/platform-node": ^0.64.4
    "@effect/platform-node-shared": ^0.19.3
    "@effect/printer-ansi": ^0.38.0
    "@effect/sql": ^0.20.9
    "@effect/sql-sqlite-node": ^0.21.9
    "@effect/typeclass": ^0.29.0
    "@effect/experimental": ^0.32.12
    "@effect/cli": ^0.48.3
    "@effect/platform-browser": ^0.48.3

