import type { TailwindPresetTheme } from '../types/theme.types.js';
import { textAlign, verticalAlign } from './aligns.js';
import { colors } from './colors.js';
import { blur, dropShadow } from './filters.js';
import {
  flex,
  flexBasis,
  flexDirection,
  flexGrow,
  flexWrap,
  justifyContent,
} from './flex.js';
import {
  fontFamily,
  fontSize,
  fontStyle,
  fontWeight,
  letterSpacing,
  lineHeight,
  textIndent,
  textShadow,
  textStrokeWidth,
  textTransform,
  wordSpacing,
} from './font.js';
import { resizeMode } from './image.js';
import {
  borderRadius,
  boxShadow,
  duration,
  easing,
  lineWidth,
  objectFit,
  overflow,
  ringWidth,
  screens,
  spacing,
  verticalBreakpoints,
} from './mixed.js';
import { aspectRatio, containers, height, maxHeight, maxWidth, width } from './size.js';
import { rotate, scale, skew, translate } from './transform.js';
import { transition } from './transition.js';

export const theme = {
  blockSize: height,
  blur,
  borderRadius,
  boxShadow,
  screens,
  colors,
  containers,
  dropShadow,
  duration,
  easing,
  flexBasis,
  flexGrow,
  fontFamily,
  fontSize,
  fontWeight,
  height,
  inlineSize: width,
  letterSpacing,
  verticalAlign,
  aspectRatio,
  textTransform,
  textAlign,
  fontStyle,
  objectFit,
  lineHeight,
  lineWidth,
  maxBlockSize: maxHeight,
  maxHeight,
  translate,
  rotate,
  skew,
  scale,
  flex,
  flexDirection,
  flexWrap,
  justifyContent,
  overflow,
  maxInlineSize: maxWidth,
  maxWidth,
  minBlockSize: maxHeight,
  minHeight: maxHeight,
  minInlineSize: maxWidth,
  minWidth: maxWidth,
  ringWidth,
  spacing,
  textIndent,
  textShadow,
  resizeMode,
  textStrokeWidth,
  transition,
  verticalBreakpoints,
  width,
  wordSpacing,
} satisfies TailwindPresetTheme;
